#!/usr/bin/env node
// ============================================================================
//  tools/vendor-deps.js — the app's third-party JS, served from our own origin
// ============================================================================
// The three user-facing pages used to pull CodeMirror, Supabase and Mermaid
// from cdnjs and jsdelivr at boot. That arrangement had four separate problems,
// and only one of them was performance:
//
//   OFFLINE      service-worker.js bypasses cross-origin requests, so none of
//                these could be precached. An offline cold start therefore had
//                no code editor and no syntax highlighting — the L3 drill, the
//                app's whole reason to exist at a desk, was dead. The service
//                worker's own header admitted it: "v2 will vendor the CDN
//                assets for true cold-start offline."
//   INTEGRITY    not one of the ten CDN tags carried an `integrity` attribute.
//                Whatever bytes the CDN returned, the page executed.
//   PINNING      `@supabase/supabase-js@2` is a RANGE. The version executing in
//                a user's browser could change without a commit here.
//   AVAILABILITY three third-party origins on the critical path, each able to
//                take the app down or be blocked by a network policy. This
//                repo already carried tools/cdp/fetch-vendor.sh purely so the
//                browser probes could work in an environment where the CDNs
//                are unreachable — a workaround for exactly this.
//
// So the bytes live in vendor/ now, committed, served same-origin, precached by
// the service worker like any other asset. Every version is exact, and every
// file's SHA-256 is recorded in vendor/lockfile.json so a refresh is verifiable
// rather than trusted.
//
//   node tools/vendor-deps.js            # download + record hashes (needs net)
//   node tools/vendor-deps.js --check    # verify committed bytes (no net)
//
// --check is what CI runs, and it is dependency- and network-free.
//
// NOT vendored: the TypeScript compiler (js/core/runner.js R.TS_URL). It is
// 8.9 MB, lazy-loaded on first use only, and only 3 of 183 lessons declare
// `"lang":"ts"` — so vendoring it would grow the repo by more than every other
// dependency combined to serve a path that never runs at boot. It stays a
// pinned, lazy fetch; the tradeoff is that those 3 lessons need network the
// first time they are opened. Revisit if TypeScript lessons become common.
const fs = require('fs');
const path = require('path');
const https = require('https');
const crypto = require('crypto');

const ROOT = path.resolve(__dirname, '..');
const VENDOR = path.join(ROOT, 'vendor');
const LOCK = path.join(VENDOR, 'lockfile.json');

// Exact versions. `@2` and `@11` ranges are resolved and frozen here — the
// whole point is that upgrading is a commit, not a CDN's decision.
const CODEMIRROR = '5.65.16';
const SUPABASE = '2.112.1';
const MERMAID = '11.16.1';
const cm = (p) => `https://cdnjs.cloudflare.com/ajax/libs/codemirror/${CODEMIRROR}/${p}`;

const DEPS = [
  { dest: 'codemirror/codemirror.css',    url: cm('codemirror.min.css') },
  { dest: 'codemirror/dracula.css',       url: cm('theme/dracula.min.css') },
  { dest: 'codemirror/codemirror.js',     url: cm('codemirror.min.js') },
  { dest: 'codemirror/javascript.js',     url: cm('mode/javascript/javascript.min.js') },
  { dest: 'codemirror/closebrackets.js',  url: cm('addon/edit/closebrackets.min.js') },
  { dest: 'codemirror/matchbrackets.js',  url: cm('addon/edit/matchbrackets.min.js') },
  { dest: 'codemirror/runmode.js',        url: cm('addon/runmode/runmode.min.js') },
  { dest: 'supabase/supabase.js',         url: `https://cdn.jsdelivr.net/npm/@supabase/supabase-js@${SUPABASE}/dist/umd/supabase.js` },
  { dest: 'mermaid/mermaid.min.js',       url: `https://cdn.jsdelivr.net/npm/mermaid@${MERMAID}/dist/mermaid.min.js` }
];

const sha256 = (buf) => crypto.createHash('sha256').update(buf).digest('hex');

function get(url, redirects = 0) {
  return new Promise((resolve, reject) => {
    if (redirects > 5) return reject(new Error(`too many redirects: ${url}`));
    https.get(url, { headers: { 'User-Agent': 'js-drill-vendor' } }, (res) => {
      if (res.statusCode >= 300 && res.statusCode < 400 && res.headers.location) {
        res.resume();
        return resolve(get(new URL(res.headers.location, url).toString(), redirects + 1));
      }
      if (res.statusCode !== 200) {
        res.resume();
        return reject(new Error(`HTTP ${res.statusCode} for ${url}`));
      }
      const chunks = [];
      res.on('data', c => chunks.push(c));
      res.on('end', () => resolve(Buffer.concat(chunks)));
    }).on('error', reject);
  });
}

async function download() {
  const lock = { _note: 'Generated by tools/vendor-deps.js. Verify with --check.', files: {} };
  for (const d of DEPS) {
    const out = path.join(VENDOR, d.dest);
    fs.mkdirSync(path.dirname(out), { recursive: true });
    process.stdout.write(`↓ ${d.dest} … `);
    const buf = await get(d.url);
    fs.writeFileSync(out, buf);
    lock.files[d.dest] = { url: d.url, sha256: sha256(buf), bytes: buf.length };
    console.log(`${(buf.length / 1024).toFixed(1)} KB`);
  }
  fs.writeFileSync(LOCK, JSON.stringify(lock, null, 2) + '\n');
  const total = Object.values(lock.files).reduce((a, f) => a + f.bytes, 0);
  console.log(`\n✓ vendored ${DEPS.length} files, ${(total / 1024 / 1024).toFixed(2)} MB → vendor/`);
}

function check() {
  if (!fs.existsSync(LOCK)) {
    console.error('✗ vendor/lockfile.json missing — run: node tools/vendor-deps.js');
    process.exit(1);
  }
  const lock = JSON.parse(fs.readFileSync(LOCK, 'utf8'));
  const problems = [];

  // Every declared dependency is present, unmodified, and still declared.
  for (const d of DEPS) {
    const rec = lock.files[d.dest];
    if (!rec) { problems.push(`${d.dest} is not in the lockfile — re-run tools/vendor-deps.js`); continue; }
    if (rec.url !== d.url) problems.push(`${d.dest} lockfile URL is stale (version changed in this script?)`);
    const p = path.join(VENDOR, d.dest);
    if (!fs.existsSync(p)) { problems.push(`${d.dest} is missing from vendor/`); continue; }
    const actual = sha256(fs.readFileSync(p));
    if (actual !== rec.sha256) problems.push(`${d.dest} does not match its recorded SHA-256 (edited by hand?)`);
  }

  // Nothing in vendor/ that we did not put there.
  const declared = new Set(DEPS.map(d => d.dest));
  const walk = (dir, base = '') => {
    if (!fs.existsSync(dir)) return;
    for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
      const rel = base ? `${base}/${e.name}` : e.name;
      if (e.isDirectory()) walk(path.join(dir, e.name), rel);
      else if (rel !== 'lockfile.json' && rel !== 'README.md' && !declared.has(rel)) {
        problems.push(`vendor/${rel} is not declared in tools/vendor-deps.js`);
      }
    }
  };
  walk(VENDOR);

  // No page may go back to fetching these over the network. Comments are
  // stripped first — the sources explain in prose why the CDNs were dropped,
  // and naming a URL in a comment is not loading it.
  //
  // JS is scanned as well as HTML. Checking only the three pages left an open
  // door: both remaining dynamic script injections live in JavaScript
  // (js/sd/02-diagrams.js loads Mermaid, js/core/runner.js loads TypeScript), so
  // pointing either back at a CDN would have passed a gate whose whole purpose
  // is "no third-party origin on the boot path".
  const BANNED = [/cdnjs\.cloudflare\.com/, /cdn\.jsdelivr\.net/, /cdn\.tailwindcss\.com/];

  // The one documented exception: the TypeScript compiler is 8.9 MB, lazy, and
  // used by 3 of 183 lessons. It is pinned and explained at its definition.
  const ALLOWED_REMOTE = /typescript@\d+\.\d+\.\d+\/lib\/typescript\.js/;

  const scanned = [];
  for (const page of ['index.html', 'system-design.html', 'diagnostic.html']) {
    const abs = path.join(ROOT, page);
    if (fs.existsSync(abs)) scanned.push([page, fs.readFileSync(abs, 'utf8').replace(/<!--[\s\S]*?-->/g, '')]);
  }
  (function walkJs(dir) {
    if (!fs.existsSync(dir)) return;
    for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
      if (['node_modules', '.git', 'archive'].includes(e.name)) continue;
      const abs = path.join(dir, e.name);
      if (e.isDirectory()) walkJs(abs);
      else if (e.name.endsWith('.js')) {
        const src = fs.readFileSync(abs, 'utf8')
          .replace(/\/\*[\s\S]*?\*\//g, '').replace(/^\s*\/\/.*$/gm, '');
        scanned.push([path.relative(ROOT, abs), src]);
      }
    }
  })(path.join(ROOT, 'js'));

  for (const [where, src] of scanned) {
    for (const re of BANNED) {
      const hit = src.match(new RegExp(`https?://[^\\s'"\`)]*${re.source}[^\\s'"\`)]*`));
      if (!hit) continue;
      if (ALLOWED_REMOTE.test(hit[0])) continue;
      problems.push(`${where} still fetches ${hit[0]} — vendor it instead`);
    }
  }

  if (problems.length) {
    console.error('\n✗ vendored dependencies are not intact:\n');
    for (const p of problems) console.error(`   ✗ ${p}`);
    console.error('');
    process.exit(1);
  }
  const total = Object.values(lock.files).reduce((a, f) => a + f.bytes, 0);
  console.log(`✓ vendor: ${DEPS.length} files intact (${(total / 1024 / 1024).toFixed(2)} MB), no CDN on any page.`);
}

if (process.argv.includes('--check')) check();
else download().catch(e => { console.error(`✗ ${e.message}`); process.exit(1); });
